-- ChannelOS IA — Database Schema
-- PostgreSQL 16 | Run once: python3 -m channelos.db.client init

-- Users (for future SaaS multi-user)
CREATE TABLE IF NOT EXISTS users (
    id          SERIAL PRIMARY KEY,
    email       TEXT UNIQUE NOT NULL,
    plan        TEXT DEFAULT 'free',
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Channels (one user → many channels)
CREATE TABLE IF NOT EXISTS channels (
    id          SERIAL PRIMARY KEY,
    user_id     INT REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    niche_key   TEXT NOT NULL,
    platform    TEXT DEFAULT 'youtube',
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Ideas generated by TrendResearchAgent
CREATE TABLE IF NOT EXISTS ideas (
    id              SERIAL PRIMARY KEY,
    channel_id      INT REFERENCES channels(id) ON DELETE SET NULL,
    title           TEXT NOT NULL,
    hook            TEXT,
    angle           TEXT,
    structure       JSONB DEFAULT '[]',
    broll_query     TEXT,
    affiliate_angle TEXT,
    viral_score     INT,
    score_reason    TEXT,
    based_on_trend  TEXT,
    brand_safe      BOOLEAN DEFAULT TRUE,
    format          TEXT DEFAULT 'single',
    status          TEXT DEFAULT 'generated',  -- generated | selected | produced | rejected
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Videos produced
CREATE TABLE IF NOT EXISTS videos (
    id              SERIAL PRIMARY KEY,
    idea_id         INT REFERENCES ideas(id) ON DELETE CASCADE,
    spoken_text     TEXT,
    caption         TEXT,
    hashtags        JSONB DEFAULT '[]',
    broll_url       TEXT,
    video_url       TEXT,
    local_path      TEXT,
    duration_sec    FLOAT,
    status          TEXT DEFAULT 'rendered',   -- rendered | downloaded | published | failed
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Cost log — per-API-call granularity
CREATE TABLE IF NOT EXISTS cost_log (
    id          SERIAL PRIMARY KEY,
    video_id    INT REFERENCES videos(id) ON DELETE SET NULL,
    idea_id     INT REFERENCES ideas(id) ON DELETE SET NULL,
    provider    TEXT NOT NULL,    -- anthropic | tavily | json2video | pexels
    operation   TEXT NOT NULL,    -- ideas | script | trends | render | broll
    units       FLOAT,
    unit_type   TEXT,             -- tokens | credits | seconds | request
    cost_usd    FLOAT DEFAULT 0,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Performance metrics (future: filled by PerformanceAgent)
CREATE TABLE IF NOT EXISTS performance (
    id              SERIAL PRIMARY KEY,
    video_id        INT REFERENCES videos(id) ON DELETE CASCADE,
    platform        TEXT,
    views           INT DEFAULT 0,
    likes           INT DEFAULT 0,
    shares          INT DEFAULT 0,
    comments        INT DEFAULT 0,
    retention_pct   FLOAT,
    hook_pattern    TEXT,
    collected_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Convenience view: cost breakdown per video
CREATE OR REPLACE VIEW video_costs AS
SELECT
    v.id         AS video_id,
    i.title      AS idea_title,
    v.created_at,
    COALESCE(SUM(c.cost_usd), 0) AS total_cost_usd,
    jsonb_object_agg(c.provider, ROUND(SUM(c.cost_usd)::numeric, 5)) AS cost_breakdown
FROM videos v
JOIN ideas i ON i.id = v.idea_id
LEFT JOIN cost_log c ON c.video_id = v.id OR c.idea_id = i.id
GROUP BY v.id, i.title, v.created_at;
